# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shel', '0008_auto_20160521_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='date_joined',
        ),
    ]
