# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shel', '0010_auto_20160521_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited', to='shel.Post'),
        ),
    ]
